### ISSUE TITLE
Bitte Job ohne Arbeit für viel Geld fixxen

### ISSUE THREAD

**Issue by L1ch-K1ng** [yfitz/testrepo#13]
Danke

**Comment by skripted96** [comment]
fixed fork. Merge Geld mit Arbeitsagentur für Arbeit und HartzIV

**Comment by SaitamaSenpai** [comment]
![grafik](https://user-images.githubusercontent.com/61866394/110588167-f31ebf00-8174-11eb-80d0-6b22ecb41e5d.png)

**Comment by L1ch-K1ng** [comment]
TO THE MOON

**Comment by SaitamaSenpai** [comment]
Timo ready for TakeOff!
![grafik](https://user-images.githubusercontent.com/61866394/110588415-47c23a00-8175-11eb-9573-e45f23fa6d63.png)
